= インストール



== Nimのインストール

Nimは3大オペレーティングシステム向けに完成された配布物が用意されており，Nimのインストールについてはいくつかの選択肢があります。

https://nim-lang.org/install.html[公式インストール手順]に従えば最新版をインストールできます。最新の機能やバグ修正が必要なら，link:https://github.com/dom96/choosenim[choosenim]と呼ばれるツールを使えば簡単に安定版と最新開発版を切り替えることが可能です。

どちらを選んでも，個々のリンク先で説明されているインストール手順に従うだけでNimはインストールされるはずです。後で，インストールがうまくいったか確認します。

Linuxを使っている場合は，使用しているディストリビューションのパッケージマネージャにNimが含まれている可能性が高いです。この方法でインストールしようとする場合は，最新版かどうか確認しましょう（何が最新版か確認するにはウェブサイト参照）。最新版でない場合は，上の二つのうちのどちらかの方法でインストールしましょう。

このチュートリアルでは安定版を使います。当初このチュートリアルはNim 0.19（2018年9月リリース）に対して執筆されましたが，Nim 1.0を含む新しい版でも動くはずです。



== 追加のツールのインストール

Nimコードはどんなエディタでも書くことは可能で，ターミナルからコンパイルと実行ができます。構文強調やコード補完を求めるなら，人気のあるコードエディタにはそのような機能を提供するプラグインがあります。

多くのNimユーザはlink:https://code.visualstudio.com/[VS Code]を好み，構文強調とコード補完にlink:https://marketplace.visualstudio.com/items?itemName=nimsaem.nimvscode[Nim extension]，迅速なコンパイルと実行にlink:https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner[Code Runner extension]を使っています。

著者はlink:https://neovim.io/[NeoVim]とlink:https://github.com/alaviss/nim.nvim[このプラグイン]（訳者はlink:https://github.com/zah/nim.vim[こちらのプラグイン]）を使って構文強調やコード補完のような機能を追加しています。

他のコードエディタで利用できるエディタサポートについては，link:https://github.com/nim-lang/Nim/wiki/Editor-Support[ウィキ]を参照してください。




== インストールの確認

インストールが成功したか確認するために，入門用の例として昔から使われているlink:https://en.wikipedia.org/wiki/%22Hello,_World!%22_program[Hello World]を書いてみます。

Nimで``Hello World``という語句を印字（スクリーンへの表示でプリンタを使った紙への印刷ではない）簡単で余計なコードは不要です。

新しいテキストファイル，例えば``helloworld.nim``に1行のコードを書くだけです。

[source]
.helloworld.nim
----
include::code/helloworld.nim[]
----

NOTE: 印字したい語句は``echo``コマンドの後に置いて二重引用符（``"``）囲む必要があります。

最初にプログラムをコンパイルしてから，走らせて期待通りに動作するか確認します。

ファイルがあるターミナルを開いてください（Linux ではファイルマネージャで右クリックして "Open Terminal here"，ウィンドウズではシフト+ 右クリックでコマンドラインを開くメニューが出ます）。

ターミナルで次のように打鍵してプログラムをコンパイルします。
[source, terminal]
----
nim c helloworld.nim
----

コンパイルに成功した後でプログラムを実行ができます。Linuxではプログラムを実行するにはターミナルで``./helloworld``ウィンドウズでは``helloworld.exe``と打鍵します。

ただ一つのコマンドでコンパイルと実行をすることもできます。次のように打鍵してください。
[source, terminal]
----
nim c -r helloworld.nim
----

NOTE: ``c``はNimにファイルをコンパルすることを命じ，``-r``は直ちに実行することを命令しています。 +
全てのコンパイラオプションを参照するには，ターミナルで``nim --help``と打鍵してください。

上述の VSCode と Code Runner 拡張機能，``Ctrl+Alt+N``を押すだけでファイルはコンパイル・実行されます。

プログラムの実行にどちらの方法を選択した場合でも，すぐに出力ウィンドウ（またはターミナル）に次のように表示されるはずです。
[source, output]
----
Hello World!
----

おめでとうございます。初めてのNimプログラムの実行に成功しました。

画面に何かを印字する方法（``echo``コマンドを利用）やプログラムのコンパイル（ターミナルで``nim c programName.nim``のように打鍵）し，それを実行する（複数の方法）を覚えました。

これからNimの基本要素を探索を始めます。これらは簡単なNimプログラムを書くために役立ちます。
