= 値の命名



プログラムの中の値に名前をつけると，分かりやすくなります。ユーザの名前を聞いて後で使うために保存しておけば，再度聞き返さずに利用することができます。

例として``pi = 3.14``で名前``pi``は値``3.14``に結びついています。
明らかに``pi``の型は（十進法の）数値です。

別の例として``firstName = Alice``では``firstName``は値``Alice``を持つ変数の名前です。
この変数の型は単語ということができるでしょう。

代入は，多くのプログラム言語で同様に動作します。
代入では _名前_, _値_, そして _型_ があります。




== 変数の宣言


Nimはlink:https://en.wikipedia.org/wiki/Type_system#STATIC[静的型付け]プログラミング言語で，代入の型は値を使う前に宣言されていなければなりません。

Nimでは変更できる値を変更できないものと区別しなければなりませんが，後ほど詳しく説明します。
変数を宣言（変更可能な代入）するには``var``キーワードを使って，次のような構文により名前と型を書きます（値は後で与えられます）。
[source]
----
var <name>: <type>
----

値がわかっているときは，変数を宣言して直ちに値を与えることができます。
[source]
----
var <name>: <type> = <value>
----
NOTE: 山括弧 (`<>`) は変更してよいものを示しています。 +
従って``<name>``は山括弧の中の文字通りの単語``name``ではなくどんな名前でも構いません。


Nimはlink:https://en.wikipedia.org/wiki/Type_inference[型推論]機能があり，明示的に型を指定しなくてもコンパイラが自動的に値から名前代入の型を検出できます。

様々な型については<<_基本データ型, 次章>>で述べます。

型推論を使うと，次のように明示的な型なしに変数の代入ができます。
[source]
----
var <name> = <value>
----


Nimにおける代入の例は次のようなものです。
[source]
----
var a: int  # <1>
var b = 7   # <2>
----
<1> 変数``a``は``int``（整数）で値は明示的に定めていません。
<2> 変数``b``は値が``7``でその型は整数として自動的に検出されています。


代入では，プログラムにおいて意味のある名前を選ぶことが重要です。単に``a``，``b`` ，``c``などとすると，すぐに混乱してきます。一つの単語よりも多くの語からなる名前を選ぶときは，通常``camelCase``スタイル（最初の文字は小文字であることに注意）で書かれます。

ただし，Nimは大文字と小文字とを区別せず，アンダスコアを無視することに注意が必要です。つまり，``helloWrold``と``hello_world``は同じです。例外として最初の文字は大文字と小文字とを区別します。変数の名前には数字やUTF-8文字を含めることができます。望むのなら絵文字も使えますが，他の人が打鍵することになる可能性に配慮する必要があります。


{nbsp}

``var``をそれぞれの変数に対して打鍵する代わりに，複数の変数（必ずしも同一の型ではない）は同じ``var``ブロックで宣言することができます。Nimではブロックは，字下げ（最初の文字の前にある同数の空白文字）が同一であるコードの一部で，既定の字下げ幅は空白2文字です。このようなブロックはNimプログラムの随所に見られ，代入に限りません。

[source]
----
var
  c = -11
  d = "Hello"
  e = '!'
----

NOTE: Nimではタブは字下げとして認められていません。 +
コードエディタを設定して``Tab``を任意の数の空白文字に置き換えることができます。 +
VS Codeでは既定は``Tab``を4つの空白文字に置き換えます。変更するには，設定（``Ctrl+,``）で``"editor.tabSize": 2``とします。

前に述べたように変数は書き換え可能，つまり変数の値は何度でも変えることができますが，型は宣言したときと同一でなければなりません。

[source]
----
var f = 7           <1>

f = -3              <2>
f = 19
f = "Hello" # エラー <3><4>
----
<1> 変数``f``は初期値``7``でその型は推定により``int`となります。
<2> ``f``の値はまず``-3``，次に``19``に変更されます。これらは両方とも整数で，元の型と同じです。
<3> ``f``の値を``"Hello"``に変更しようとすると， エラーが発生します。``Hello``は数値ではなくので，``f``の型を整数から文字列にしようとしています。
<4>``# エラー``はコメントです。Nimコード中のコメントは文字``#``の後に書きます。これに続く全ての文字は行の終わりまで無視されます。




== 書き換え不可の代入

キーワード``var``を使って宣言された変数とは異なり，Nimにはあと2種類の代入があります。これらの値は変えることができません。一つはキーワード``const``，もう一つはキーワード``let``を使って宣言されます。



=== Const

キーワード``const``で宣言された書き換え不可な代入に用いられる値は，コンパイル時（プログラム実行前）に既知なければなりません。

例えば，重力加速度を``const g = 9.81``あるいは円周率を``const pi = 3.14``として宣言することができます。これらの値は事前に分かっていてプログラムの実行の間不変です。

[source]
----
const g = 35
g = -27         # エラー <1>

var h = -5
const i = h + 7 # エラー <2>
----
<1> 定数の値は変えられません。
<2> 変数``h``はコンパイル時に評価されません（これは変数でその値はプログラムの実行中にかわりえます。）， 従って定数``i``の値はコンパイル時には知り得ないので，エラーが発生します。

プログラミング言語によっては，定数の名前を``ALL_CAPS`のように全て大文字で書く習慣があります。Nimの定数は他の変数と同様に書きます。



=== Let

``let``で宣言された書き換え不可の代入は，コンパイル時に既知である必要はなく，その値はプログラムの実行中いつでも設定できますが，ひとたび設定したら値を変えることはできません。

[source]
----
let j = 35
j = -27 # エラー <1>

var k = -5
let l = k + 7   <2>
----
<1> 書き換え不可の値は変更できません。
<2> ``const``の例とは対照的に，これは動作します。

実際には，``let``は``const``よりも多く使われます。

``var``を何にでも使うことはできますが，``let``を基本とすべきです。``var``は変更することになる変数のみに使いましょう。
