= 流れの制御


これまでのプログラムは全ての行が必ず実行されていました。流れを制御する文を使うと，コードの一部がある真偽条件が成り立つ場合にのみ実行させるようにすることができます。

プログラムを道路に例えるならば，流れの制御は分かれ道であり，その一つを条件により選択します。例）もし（__if__）卵がある値段以下なら買う。もし（__if__）雨が降っていれば傘を持っていく，さもなくば（__else__）サングラスを持っていく。

https://en.wikipedia.org/wiki/Pseudocode[擬似コード]で書くと次のようになります。

[source]
----
if eggPrice < wantedPrice:
  buyEggs

if isRaining:
  bring umbrella
else:
  bring sunglasses
----

Nimの文法は，以下に示すようによく似ています。





== If文

上に示したif文はプログラムの中で最も簡単な分岐です。

Nimの文法でif文は以下のように書きます。

[source]
----
if <condition>:     <1>
  <indented block>  <2>
----

<1> ``condition``は真偽型でなくてはなりません。真偽値または関係演算子，論理式やその組合せ。
<2> ``if``の行に続く全ての行は二つの空白文字で字下げし，同じブロックとして条件が``true``のときにのみ実行されます。

If文は入れ子にできます。すなわち，一つのifブロックの内側に別のif文を入れることができます。

[source]
.if.nim
----
include::{source-dir}/if.nim[]
----
<1> 最初の条件が真で二番目が偽なので中``echo``は実行されません。
<2> 二つの条件が真で両方の行が印字されます。
<3> 最初の条件が偽なので，このブロックの内側の全ての行は無視され，何も印字されません。
<4> ``if``文の内側の論理``and``。

[source, output]
----
a is smaller than b
b is smaller than c
not only that, b is *much* smaller than c
----



=== Else

Ifブロックの後に続くelseを使うと，if文の条件が偽であるときに実行される分岐を作ることができます。

[source]
.else.nim
----
include::{source-dir}/else.nim[]
----

[source, output]
----
d is a large number
e is a small number
----

NOTE: If文が``false``のときだけブロックを実行するには，``not``演算子を使って条件を否定します。




=== Elif

Elifは"else if"の短縮形で，複数のif文をつなげることができます。

プログラムは真となるまで文を試します。その後の全ての文は無視されます。

[source]
.elif.nim
----
include::{source-dir}/elif.nim[]
----

[source, output]
----
f is larger than 1000
g is smaller than 1000
----

NOTE: ``g``の場合``g``は三つの条件全てを満たしますが，最初の分岐だけが実行され，後の全ての分岐は実行が省略されます。




== Case

Case文は複数の可能性から一つを選択する別の方法で，複数の``elif``のあるif文に似ています。``case``文は複数の真偽条件を取らず，異なる値とそれに分岐を対応させます。

次のようなif-elifブロックで書かれたコードは

[source]
----
if x == 5:
  echo "Five!"
elif x == 7:
  echo "Seven!"
elif x == 10:
  echo "Ten!"
else:
  echo "unknown number"
----
はcase文で次のように書けます。

[source]
----
case x
of 5:
  echo "Five!"
of 7:
  echo "Seven!"
of 10:
  echo "Ten!"
else:
  echo "unknown number"
----

If文とは異なり，case文はとりうる__全て__の場合を包含しなくてはなりません。該当しない場合があるときは``else: discard``を使うことができます。

[source]
.case.nim
----
include::{source-dir}/case.nim[]
----
<1> 必要のなのは``h``の三つの値だけですが，とりうる全ての場合（他の全ての文字）を含めるためにこの行が必要です。これがないとコンパイルが通りません。

[source, output]
----
You've chosen y
----



複数の値に対して同じ動作をさせる場合は，それぞれの分岐に対して複数の値を割り当てることもできます。
[source]
.multipleCase.nim
----
include::{source-dir}/multipleCase.nim[]
----

[source, output]
----
i is odd
----
