= 繰り返し



繰り返し（ループ）は，もう一つの流れの制御構造でコードの一部を複数回実行することを可能にするものです。

この章では二種類のループを学びます。

* forループ: 決まった回数の繰り返し
* whileループ: 条件が満たされる間繰り返し


== Forループ 

forループの文法は
[source]
----
for <loopVariable> in <iterable>:
  <loop body>
----

伝統的に``i``がループ変数``loopVariable``の名前として使われていますが，なんでも構いません。この変数はループの内側だけで使えます。ループが終わった後は，ループ変数は破棄されます。

``iterable``は反復可能なオブジェクトです。これまでに述べた方のうち，文字列は反復可能オブジェクトです（いろいろな反復可能な型は<<_コンテナ, 次章>>に登場します）。

``loop body``の全ての行は反復の度に実行されるため，コードの繰り返される部分を効率的に書くことができます。

{nbsp}

Nimで（整数型）数値の範囲にわたって反復したいときは，``iterable``の文法は ``start .. finish``で``start``と``finish``は数値です。このように書くと，``start``と``finish``の間の数値を``finish``を含めて反復します。既定の反復可能な範囲では，``start``は``finish``よりも小さくなくてはなりません。

ある数値の手前まで（その数値を含まない）反復では``..<``を使います。

[source]
.for1.nim
----
include::{source-dir}/for1.nim[]
----
<1> 反復を``..``を使って行う場合，範囲の始端・終端の両方が含まれます。
<2> 同じ範囲の反復を``..<``を使って行うと，終端の手前までで終端は含まれません。

[source, output]
----
5
6
7
8
9

5
6
7
8
----


1でない刻み幅を用いて数値の範囲について反復する場合，``countup``が用いられます。``countup``には，開始値，終了値（範囲に含まれる）と刻み幅を指定します。

[source]
.for2.nim
----
include::{source-dir}/for2.nim[lines=1..2]
----
<1> 0から16まで刻み幅4で小さい方から大きい方に数えます。終端（16）は範囲に含まれます。

[source, output]
----
0
4
8
12
16
----


``start``が``finish``より大きい数値の範囲にわたって反復するときは，``countdown``と呼ばれる類似の関数を使います。大きい方から小さい方に数えているにも関わらず，刻み幅は正です。

[source]
.for2.nim
----
include::{source-dir}/for2.nim[lines=5..12]
----
<1> 大きい数値から小さい数値に向かって反復するには``countdown``を使わなければなりません。（``..``演算子は開始する数値が終了する数値よりも小さい場合にのみ使えます。
<2> 大きい方から小さい方に数えるにも関わらず，刻み幅は正なくてはなりません。

[source, output]
----
4
3
2
1
0

-3
-5
-7
-9
----


文字列は反復可能なので，forループを使って文字列に含まれる文字を一つづつ反復していくことができます（この手の反復は__for-each__ループとも呼ばれます）。

[source]
.for3.nim
----
include::{source-dir}/for3.nim[lines=1..4]
----

[source, output]
----
a
l
p
h
a
b
e
t
----


反復カウンタ（0始まり）も必要な場合は，``for <counterVariable>, <loopVariable> in <iterator>:``という文法が使えます。これは，ある反復可能オブジェクトについて反復し，同時に別の反復可能オブジェクトの同じ位置の値を使うときに便利です。

[source]
.for3.nim
----
include::{source-dir}/for3.nim[lines=7..9]
----

[source, output]
----
letter 0 is: a
letter 1 is: l
letter 2 is: p
letter 3 is: h
letter 4 is: a
letter 5 is: b
letter 6 is: e
letter 7 is: t
----




== Whileループ 

Whileループはif文に似ていますが，コードのブロックを条件が真の間実行し続けます。これはループが何回実行されるか事前に分からないときに使われます。

ループがある時点で必ず終了するようにして，link:https://en.wikipedia.org/wiki/Infinite_loop[無限ループ]にならないようにします。

[source]
.while.nim
----
include::{source-dir}/while.nim[]
----
<1> この条件は新しいループに入る度に検査され，内側のコードが実行されます。
<2> ``inc``は``a``を一つ増やします。``a = a + 1``または``a += 1``と書くのと同じです。

[source, output]
----
a is: 1
a is: 2
a is: 3
final value of a: 4
----




== Breakとcontinue

``Break``文は通常ある条件が満たされた場合に先にループから出るために使います。

次の例では，``break``文を伴うif文がなければ，``i``が1000になるまで印字が継続します。``break``分があると，``i``が3になると（値を印字する前に）直ちにループを出ます

[source]
.break.nim
----
include::{source-dir}/break.nim[]
----

[source, output]
----
1
2
----

{nbsp}

``continue``文は直ちにループの次の反復を実行し，現在の反復の残り行は実行されません。次のコードで3と6が出力にないことに注意してください。

[source]
.continue.nim
----
include::{source-dir}/continue.nim[]
----

[source, output]
----
1
2
4
5
7
8
----




== 練習問題

1. https://en.wikipedia.org/wiki/Collatz_conjecture[コラッツの問題]は有名な数学の問題で，ルールは単純です。まず数値を選びます。奇数なら3を加えて1を足します。もし偶数なら2で割ります。この手順を1になるまで続けます。例。5 -> 奇数 -> 3*5 + 1 = 16 -> 偶数 -> 16 / 2 = 8 -> 偶数 -> 4 -> 2 -> 1 -> end! +
整数を（書き換え可能な変数として）選びコラッツの問題の各ステップを印字するプログラムを書いてください。（ヒント。``div``を割り算に使います。）

2. 書き換え不可の変数を作り，フルネームを格納します。Forループ書いて文字列を要素について反復し母音（a, e, i, o u）だけ印字してください（ヒント。``case``文を使って分岐毎に複数の値します。

3. https://en.wikipedia.org/wiki/Fizz_buzz[Fizz buzz]は子供の遊びで基本的なプログラミングの知識を試すためにも使われます。数は1から増える方向に数えます。数値が3の倍数なら _fizz_，5の倍数なら_buzz_で置き換え，もし数値が15（3と5両方）なら_fizzbuzz_で置き換えます。最初の数回は次のようになります。1, 2, fizz, 4, buzz, fizz, 7, ... +
Fizz buzzの最初の30回を印字するプログラムを書いてください（ヒント。除算の順序のテストに注意してください。

4. 前の問題でインチをセンチメートルにまたはその逆に変換しました。複数の値の変換表を作ってください。表の例を示します。+
----
in	| cm
----------------
1	| 2.54
4	| 10.16
7	| 17.78
10	| 25.4
13	| 33.02
16	| 40.64
19	| 48.26
----
