= モジュール



これまでは，新しいNimのファイルを作ると既定で使える機能を学んできました。モジュールを使うと既定から拡張して，特定の目的のために用いる機能を使いすることができます。

よく用いられるNimのモジュールを挙げます。

* `strutils`: 文字列を扱う追加の機能
* `sequtils`: シーケンスに対する追加の機能
* `math`: 数学関数（対数，平方根 ...), 三角関数（sin, cos, ...）
* `times`: 時間を測定したり扱ったりする。

https://nim-lang.org/docs/lib.html[標準ライブラリ]やlink:https://nimble.directory/[nimbleパッケージマネージャ]にはもっとたくさんあります。




== モジュールのインはポート

モジュールをインポートして機能を全て使いたいときは``import <moduleName>``をファイルに書きます。通常ファイルの先頭に書いて，コードが何を使うか分かるようにします。

[source]
.stringutils.nim
----
include::{source-dir}/stringutils.nim[]
----
<1> https://nim-lang.org/docs/strutils.html[strutils]をインポート。
<2> ``strutils``モジュールから``split``を使い，文字列を単語の列に分割します。
<3> ``toUpperAscii``は全てのASCII文字を大文字にします。
<4> ``repeat``も``strutils``モジュールからで。文字や文字列全体を指定回数繰り返します。

[source, output]
----
@["My", "string", "with", "whitespace."]
MY STRING WITH WHITESPACE.
!!!!!
----

NOTE: 他のプログラミング言語（特にPython）のユーザは，Nimkのインポートの動作は「誤り」に見えるかもしれません。その場合はlink:https://narimiran.github.io/2019/07/01/nim-import.html[こちら]をご覧ください。

{nbsp}


[source]
.maths.nim
----
include::{source-dir}/maths.nim[]
----
<1> https://nim-lang.org/docs/math.html[math]をインポート。
<2> 度をラジアンに変換するのに``degToRad``を使います。
<3> ``sin``にはラジアンを与えます。結果を小数第二位で丸めるために（これも``math``由来の）roundを使います（そうしないと結果は0.4999999999999999のようになるでしょう）。
<4> Mathモジュールの `^` 演算子は数値の冪乗の計算につかいます。

[source, output]
----
0.5235987755982988
0.5
32
----




== 自前のモジュール

コードがプロジェクトのコードが多くなり，特定のことをする部品に分けることが適切であることがよくあります。二つのファイルを一つのフォルダの中に作り，``firstFile.nim``と``secondFile.nim``と名付けた場合，一方から他方は次のようにインポートできます。

[source]
.firstFile.nim
----
proc plus*(a, b: int): int = <1>
  return a + b

proc minus(a, b: int): int = <2>
  return a - b
----
<1> ``plus``手続きには，名前の後にアステリスク（`*`) がついていることに注目してください。これはNimにこのファイルをインポートした別のファイルはこの手続きを使えることを伝えています。
<2> 対照的にこの手続きは，このファイルをインポートしたファイルからは見えません。

[source]
.secondFile.nim
----
import firstFile          <1>

echo plus(5, 10)          <2>
echo minus(10, 5) # error <3>
----
<1> ここで``firstFile.nim``をインポートします。ここには``.nim``拡張子は不要です。
<2> ``firstFile``に定義されており見えるので，これは問題なく動作し``15``が印字されます。
<3> しかしこれはエラーが発程します。``minus``手続きは名前の後ろにアステリスクが付いていないので見えないからです。


これら二つのファイルよりももっとあるときは一つ（またはそれ以上の）サブディレクトリに整理することができます。ディレクトリ構造が次のようであるとします。

[source, output]
----
.
├── myOtherSubdir
│   ├── fifthFile.nim
│   └── fourthFile.nim
├── mySubdir
│   └── thirdFile.nim
├── firstFile.nim
└── secondFile.nim
----


``secondFile.nim``にその他の全てのファイルをインポートするには次のようにします。

[source]
.secondFile.nim
----
import firstFile
import mySubdir/thirdFile
import myOtherSubdir / [fourthFile, fifthFile]
----
