= ユーザ入力の取り扱い



これまでに学んだ項目（基本データ型とコンテナ，流れの制御，ループ）を使えば多数の簡単なプログラムが書けます。

この章ではプログラムをより対話型にする方法を学びます。そのためには，ファイルからデータを読み込んだり，ユーザに入力を求めたりする手段が必要となります。




== ファイルからの読み込み

``people.txt``という名前のファイルがNimコードと同じディレクトリにあったといます。ファイルの中身は次のようなものです。

[source]
.people.txt
----
include::{source-dir}/people.txt[]

----

プログラム中でファイルの中身を名前のリスト（シーケンス）として使います。

[source]
.readFromFile.nim
----
include::{source-dir}/readFromFile.nim[]
----
<1> ファイルの中身を読むには``readFile``手続きを使い，読むファイルのパスを与えます（Nimのプログラムと同じディレクトリにある場合はファイル名だけで十分です）。読み込み結果は複数行の文字列になります。
<2> 複数行の文字列を文字列のシーケンス（個々の文字列は一行の全ての内容を含みます）に分割するには，``strutils``モジュールの``splitLines``を使います。

[source, output]
----
Alice A.
Bob B.
Carol C.
            <1>
@["Alice A.", "Bob B.", "Carol C.", ""] <2>
----
<1> 元のファイルには最後の改行（最後が空行）があり，ここにも残っています。
<2> 最後の改行のために，シーケンスは想定よりも長くなっています。

最後の改行の問題を解決するためには，``strutils``の``strip``手続きをファイルを読んだ後に使います。これは，文字列の最初と最後の空白文字と呼ばれるものを除去します。空白文字は，スペースを作る，スペースや改行，タブなどが含まれます。

[source]
.readFromFile2.nim
----
include::{source-dir}/readFromFile2.nim[]
----
<1> ``strip``によって期待通りの結果が得られます。

[source, output]
----
Alice A.
Bob B.
Carol C.
@["Alice A.", "Bob B.", "Carol C."]
----




== ユーザ入力の読み取り

ユーザと対話するには，入力を求めて処理し，利用する必要があります。link:https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)[標準入力（stdin）]から読むため``readLine``手続に``stdin``を渡します。

[source]
.interaction1.nim
----
include::{source-dir}/interaction1.nim[]
----
<1> ``name``の型は文字列と推定されます。


[source, output]
----
Please enter your name:
        <1>
----
<1> ユーザの入力を待ちます。名前を書いて``Enter``を押すとプログラムは再開します。

[source, output]
----
Please enter your name:
Alice
Hello Alice, nice to meet you!
----

NOTE: 古い版のVS Codeだといつもの方法 （``Ctrl+Alt+N``）で動作しません。出力ウィンドウではユーザの入力ができないからです。ターミナルで例を実行する必要があります。 +
VS Codeの新しい版ではこのような制限はありません。




== 数値の取り扱い

ファイルやユーザ入力を読んだ結果は常に文字列になります。数値として使うには，文字列を数値に変換す必要があります。ここでも``strutils``モジュールを使い，``parseInt``で整数または``parseFloat``で浮動小数点数にします。

[source]
.interaction2.nim
----
include::{source-dir}/interaction2.nim[]
----
<1> 文字列を整数に変換。このように書いた場合ユーザは有効な整数を入力するものと想定しています。ユーザが``'79``または``ninety-three``と入力したらどうなるでしょうか。試してみてください。

[source, output]
----
Please enter your year of birth:
1934
You are 84 years old.
----

{nbsp}

Nimコードと同じディレクトリにファイル``numbers.txt``があり，次のような中身だとします。

[source]
.numbers.txt
----
include::{source-dir}/numbers.txt[]
----

このファイルを読んで，与えられた数値の合計と平均を求めるには，次のようにします。

[source]
.interaction3.nim
----
include::{source-dir}/interaction3.nim[]
----
<1> 複数のモジュールをインポートします。``strutils``は``strip``と``splitLines``，``sequtils``は``map``，そして``math``は``sum``を提供します。
<2> 最後の改行を取り除き，行を分割して文字列のシーケンスを作ります。
<3> ``map``は手続（この場合は``parseFloat``）をコンテナのそれぞれのメンバに適用します。 それぞれの文字列を浮動小数点数にし，新しい浮動小数点数のシーケンスを返します。
<4> ``math``モジュールの``sum``を使ってシーケンスの全ての要素の和を求めます。
<5> ``sunNums``は浮動小数点数なので，シーケンスの長さを浮動小数点数に変換する必要があります。

[source, output]
----
226.15
45.23
----




== 練習問題

1. ユーザに身長と体重を尋ねてください。link:https://en.wikipedia.org/wiki/Body_mass_index[BMI]インデックスを計算します。BMIの値と分類を報告ユーザにしてください。

2. <<_練習問題_4, コラッツ予想の練習問題>>で，今度はユーザに最初の数を聞くプログラムを作ってください。結果のシーケンスを印字してください。

3. 反転してほしい文字列を聞いてください。文字列を取り反転したものを返す手続きを作ってください。例えば，ユーザが``Nim-lang``と入れたら手続きが``gnal-miN``と返すようにします。（ヒント: 要素指定と``countdown``を使います。）
